CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY,
    credit_limit NUMERIC(12,2),
    age INTEGER,
    gender INTEGER,
    education INTEGER,
    marital_status INTEGER,
    num_delayed_months INTEGER,
    max_delay INTEGER,
    avg_delay NUMERIC(8,3),
    recent_delay INTEGER,
    utilization_sep NUMERIC(10,4),
    avg_utilization NUMERIC(10,4),
    max_utilization NUMERIC(10,4),
    total_payment_6m NUMERIC(14,2),
    recent_payment_3m NUMERIC(14,2),
    older_payment_3m NUMERIC(14,2)
);

CREATE TABLE customer_segments (
    customer_id INTEGER PRIMARY KEY,
    customer_segment INTEGER NOT NULL,
    CONSTRAINT customer_segments_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);

CREATE TABLE risk_predictions (
    customer_id INTEGER PRIMARY KEY,
    pd NUMERIC(8,6) NOT NULL,
    risk_tier VARCHAR(10) NOT NULL,
    actual_default INTEGER,
    model_name VARCHAR(100) NOT NULL,
    prediction_date DATE NOT NULL,
    CONSTRAINT risk_predictions_customer_id_fkey
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id)
);

CREATE TABLE model_metadata (
    model_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name VARCHAR(100) NOT NULL,
    model_version VARCHAR(50),
    classification_threshold NUMERIC(6,4),
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
